from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


DEFAULT_CATEGORIES = ["cs.RO", "cs.CV", "cs.LG", "cs.AI", "eess.SY"]


@dataclass(frozen=True)
class EmbodiedTopic:
    key: str
    label: str
    label_zh: str
    tree_label: str
    asset_key: str
    weight: float
    include: Sequence[str]
    exclude: Sequence[str] = ()


EMBODIED_TOPICS: Sequence[EmbodiedTopic] = (
    EmbodiedTopic(
        key="foundation",
        label="Foundation Model",
        label_zh="基座模型",
        tree_label="基座树",
        asset_key="vla",
        weight=3.8,
        include=(
            "vision-language model",
            "vision-language models",
            "vision language model",
            "vision language models",
            "vlm",
            "vlms",
            "large vision-language model",
            "large vision language model",
            "multimodal large language model",
            "multimodal large language models",
            "multimodal model",
            "multimodal models",
            "embodied vlm",
            "robot vlm",
            "vision-language-action",
            "vision-language-action model",
            "vision-language-action models",
            "vision language action",
            "vision language action model",
            "vision language action models",
            "vla",
            "vlas",
            "embodied vla",
            "robot vla",
            "robot foundation model",
            "robot foundation models",
            "robotic foundation model",
            "robotic foundation models",
            "robot policy",
            "action model",
            "action models",
            "large action model",
            "large action models",
            "generalist robot",
            "generalist robotics",
            "generalist policy",
            "generalist policies",
            "multimodal policy",
            "multimodal policies",
            "embodied foundation model",
            "embodied generalist",
            "openvla",
            "rt-2",
            "vla reinforcement learning",
            "vla rl",
            "rl-vla",
            "reinforcement learning for vla",
            "policy optimization for vla",
            "vla policy optimization",
            "vla fine-tuning",
            "vla finetuning",
            "vla post-training",
            "vla post training",
            "world model",
            "world models",
            "world action model",
            "world action models",
            "wam",
            "action-conditioned",
            "action conditioned",
            "dynamics model",
            "environment model",
            "spatial memory",
            "scene graph",
            "generative world",
            "latent dynamics",
            "forward model",
            "predictive model",
            "predictive models",
            "video prediction",
            "future prediction",
            "model-based control",
            "model based control",
        ),
    ),
    EmbodiedTopic(
        key="ego_umi",
        label="Ego / UMI",
        label_zh="第一视角 / UMI",
        tree_label="第一视角树",
        asset_key="hardware",
        weight=3.1,
        include=(
            "egocentric",
            "ego-centric",
            "ego centric",
            "first-person",
            "first person",
            "first-person video",
            "first person video",
            "ego4d",
            "ego-exo",
            "ego exo",
            "hand camera",
            "hand-object",
            "hand object",
            "hand-object interaction",
            "hand object interaction",
            "in-hand",
            "in hand",
            "human manipulation video",
            "human manipulation videos",
            "human demonstration",
            "human demonstrations",
            "human video",
            "human videos",
            "human-to-robot",
            "human to robot",
            "teleoperated demonstration",
            "teleoperated demonstrations",
            "umi",
            "universal manipulation interface",
            "wearable camera",
            "wrist camera",
        ),
    ),
    EmbodiedTopic(
        key="perception_spatial",
        label="Perception / Spatial",
        label_zh="感知 / 空间",
        tree_label="感知树",
        asset_key="embodied_ai",
        weight=2.7,
        include=(
            "3d perception",
            "scene understanding",
            "spatial understanding",
            "spatial intelligence",
            "affordance",
            "affordances",
            "pose estimation",
            "segmentation",
            "object detection",
            "object-centric",
            "visual representation",
            "visual representations",
            "depth estimation",
            "point cloud",
            "point clouds",
            "3d reconstruction",
            "3d scene",
            "occupancy",
            "semantic mapping",
            "object pose",
            "object poses",
        ),
        exclude=("disembodied",),
    ),
    EmbodiedTopic(
        key="learning_control",
        label="Learning / Control",
        label_zh="学习 / 控制",
        tree_label="机械松树",
        asset_key="robotics",
        weight=2.8,
        include=(
            "reinforcement learning",
            "robot learning",
            "imitation learning",
            "behavior cloning",
            "behaviour cloning",
            "policy learning",
            "policy optimization",
            "policy distillation",
            "diffusion policy",
            "diffusion policies",
            "skill learning",
            "skill acquisition",
            "control",
            "controller",
            "controllers",
            "trajectory",
            "trajectory optimization",
            "motion planning",
            "task planning",
            "long-horizon",
            "long horizon",
            "model predictive control",
            "mpc",
            "visual servoing",
            "fine-tuning",
            "finetuning",
            "closed-loop control",
            "closed loop control",
            "manipulation",
            "manipulate",
            "manipulator",
            "grasping",
            "grasp",
            "dexterous",
            "dexterous hand",
            "dexterous manipulation",
            "bimanual",
            "bimanual manipulation",
            "mobile manipulation",
            "tool use",
            "tool-use",
        ),
        exclude=("chatbot", "botnet", "web robot", "software robot"),
    ),
    EmbodiedTopic(
        key="navigation_mobility",
        label="Navigation / Mobility",
        label_zh="导航 / 移动",
        tree_label="路标树",
        asset_key="navigation",
        weight=2.6,
        include=(
            "navigation",
            "navigate",
            "objectnav",
            "object navigation",
            "vln",
            "vision-language navigation",
            "path planning",
            "trajectory planning",
            "exploration",
            "locomotion",
            "mobile robot",
            "mobile robots",
            "slam",
            "localization",
            "mapping",
            "mapless navigation",
            "embodied navigation",
            "nav",
        ),
    ),
    EmbodiedTopic(
        key="data_loop",
        label="Data Loop",
        label_zh="数据闭环",
        tree_label="数据树",
        asset_key="dataset",
        weight=2.7,
        include=(
            "data engine",
            "data engines",
            "data flywheel",
            "data flywheels",
            "data closed loop",
            "closed-loop data",
            "closed loop data",
            "active data collection",
            "continual data collection",
            "autonomous data collection",
            "robot data collection",
            "real robot data",
            "real-world robot data",
            "real world robot data",
            "data curation",
            "dataset curation",
            "automatic labeling",
            "auto-labeling",
            "auto labeling",
            "data pipeline",
            "data pipelines",
            "data mixture",
            "data mixtures",
            "data scaling",
            "post-training data",
            "robot data engine",
            "robot data flywheel",
            "rollout collection",
            "rollout data",
            "real robot rollout",
            "real robot rollouts",
        ),
    ),
    EmbodiedTopic(
        key="simulation_synthetic",
        label="Simulation / Synthetic Data",
        label_zh="仿真 / 合成数据",
        tree_label="仿真树",
        asset_key="simulation",
        weight=2.6,
        include=(
            "simulation",
            "simulator",
            "simulators",
            "simulated",
            "sim-to-real",
            "sim to real",
            "sim2real",
            "domain randomization",
            "digital twin",
            "digital twins",
            "synthetic",
            "synthetic data",
            "synthetic dataset",
            "synthetic datasets",
            "synthetic trajectory",
            "synthetic trajectories",
            "synthetic demonstration",
            "synthetic demonstrations",
            "synthetic scene",
            "synthetic scenes",
            "procedural generation",
            "generative data",
            "generated data",
            "embodied simulation",
            "physics simulator",
            "physics simulation",
            "mujoco",
            "isaac sim",
            "isaacsim",
            "robosuite",
            "metaworld",
        ),
    ),
    EmbodiedTopic(
        key="evaluation_benchmark",
        label="Evaluation / Benchmark",
        label_zh="评测 / 基准",
        tree_label="石碑树",
        asset_key="dataset",
        weight=2.2,
        include=(
            "benchmark",
            "benchmarks",
            "dataset",
            "datasets",
            "evaluation",
            "evaluation suite",
            "diagnostic benchmark",
            "leaderboard",
            "metric",
            "metrics",
            "protocol",
            "testbed",
            "test bed",
            "stress test",
            "stress testing",
            "reliability",
            "safety",
            "deployment",
            "generalization",
            "robustness",
            "real-world dataset",
            "robot dataset",
            "robotics dataset",
            "embodied dataset",
        ),
    ),
    EmbodiedTopic(
        key="hardware_teleop",
        label="Hardware / Teleop",
        label_zh="本体硬件 / 遥操作",
        tree_label="本体树",
        asset_key="hardware",
        weight=2.5,
        include=(
            "robot body",
            "hardware",
            "humanoid",
            "gripper",
            "morphology",
            "whole-body",
            "whole body",
            "end-effector",
            "teleoperation",
            "wearable",
            "sensor",
            "sensors",
            "actuator",
            "actuators",
            "tactile",
            "haptic",
            "force feedback",
            "embodiment",
        ),
    ),
)


LEGACY_KEYWORD_GROUP_NAMES = {
    "Embodied Intelligence",
    "Robotics Core",
    "VLA and Robot Foundation Models",
    "VLA / Foundation",
    "World Model / WAM",
    "Datasets and Benchmarks",
    "World Models and Data Loop",
    "First Person and UMI",
    "Reasoning / Planning",
    "Manipulation",
    "Simulation / Data Loop",
    "Robot Body and Hardware",
}
