from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


DEFAULT_CATEGORIES = ["cs.RO", "cs.CV", "cs.LG", "cs.AI", "eess.SY"]


@dataclass(frozen=True)
class EmbodiedTopic:
    key: str
    label: str
    label_zh: str
    tree_label: str
    asset_key: str
    weight: float
    include: Sequence[str]
    exclude: Sequence[str] = ()


EMBODIED_TOPICS: Sequence[EmbodiedTopic] = (
    EmbodiedTopic(
        key="foundation",
        label="VLA / Foundation",
        label_zh="VLA / 基座模型",
        tree_label="果树",
        asset_key="vla",
        weight=3.5,
        include=(
            "vision-language-action",
            "vision language action",
            "vla",
            "robot foundation model",
            "robot foundation models",
            "robot policy",
            "action model",
            "generalist robot",
            "generalist robotics",
            "multimodal policy",
            "embodied foundation model",
        ),
    ),
    EmbodiedTopic(
        key="perception_spatial",
        label="Perception / Spatial",
        label_zh="感知 / 空间",
        tree_label="感知树",
        asset_key="embodied_ai",
        weight=2.7,
        include=(
            "3d perception",
            "scene understanding",
            "spatial understanding",
            "spatial intelligence",
            "affordance",
            "affordances",
            "pose estimation",
            "segmentation",
            "object detection",
            "object-centric",
            "visual representation",
        ),
        exclude=("disembodied",),
    ),
    EmbodiedTopic(
        key="world_model",
        label="World Model / WAM",
        label_zh="世界模型 / WAM",
        tree_label="水晶树",
        asset_key="world_model",
        weight=3.2,
        include=(
            "world model",
            "world models",
            "world action model",
            "world action models",
            "wam",
            "action-conditioned",
            "action conditioned",
            "dynamics model",
            "environment model",
            "spatial memory",
            "scene graph",
            "generative world",
        ),
    ),
    EmbodiedTopic(
        key="reasoning_planning",
        label="Reasoning / Planning",
        label_zh="推理 / 规划",
        tree_label="路标树",
        asset_key="navigation",
        weight=3.0,
        include=(
            "reasoning",
            "planning",
            "task planning",
            "long-horizon",
            "long horizon",
            "decision making",
            "verification",
            "hierarchical",
            "agentic",
            "task execution",
        ),
    ),
    EmbodiedTopic(
        key="learning_control",
        label="Learning / Control",
        label_zh="学习 / 控制",
        tree_label="机械松树",
        asset_key="robotics",
        weight=2.8,
        include=(
            "reinforcement learning",
            "imitation learning",
            "policy learning",
            "policy optimization",
            "control",
            "controller",
            "trajectory",
            "fine-tuning",
            "finetuning",
            "closed-loop control",
            "closed loop control",
        ),
        exclude=("chatbot", "botnet", "web robot", "software robot"),
    ),
    EmbodiedTopic(
        key="manipulation",
        label="Manipulation",
        label_zh="操作 / 抓取",
        tree_label="工具树",
        asset_key="manipulation",
        weight=2.8,
        include=(
            "manipulation",
            "manipulate",
            "manipulator",
            "grasping",
            "grasp",
            "dexterous",
            "dexterous hand",
            "bimanual",
            "mobile manipulation",
            "tool use",
            "tool-use",
        ),
    ),
    EmbodiedTopic(
        key="navigation_mobility",
        label="Navigation / Mobility",
        label_zh="导航 / 移动",
        tree_label="路标树",
        asset_key="navigation",
        weight=2.6,
        include=(
            "navigation",
            "navigate",
            "objectnav",
            "object navigation",
            "vln",
            "vision-language navigation",
            "path planning",
            "exploration",
            "locomotion",
            "mobile robot",
        ),
    ),
    EmbodiedTopic(
        key="simulation_data_loop",
        label="Simulation / Data Loop",
        label_zh="仿真 / 数据闭环",
        tree_label="仙人掌树",
        asset_key="simulation",
        weight=2.6,
        include=(
            "simulation",
            "simulator",
            "sim-to-real",
            "sim to real",
            "digital twin",
            "synthetic data",
            "data engine",
            "data flywheel",
            "data closed loop",
            "closed-loop data",
        ),
    ),
    EmbodiedTopic(
        key="evaluation_benchmark",
        label="Evaluation / Benchmark",
        label_zh="评测 / 基准",
        tree_label="石碑树",
        asset_key="dataset",
        weight=2.2,
        include=(
            "benchmark",
            "benchmarks",
            "dataset",
            "datasets",
            "evaluation",
            "evaluation suite",
            "diagnostic benchmark",
            "reliability",
            "safety",
            "deployment",
            "real-world dataset",
            "robot dataset",
            "robotics dataset",
            "embodied dataset",
        ),
    ),
    EmbodiedTopic(
        key="hardware_teleop",
        label="Hardware / Teleop",
        label_zh="本体硬件 / 遥操作",
        tree_label="本体树",
        asset_key="hardware",
        weight=2.5,
        include=(
            "robot body",
            "hardware",
            "humanoid",
            "gripper",
            "morphology",
            "whole-body",
            "whole body",
            "end-effector",
            "teleoperation",
            "umi",
            "universal manipulation interface",
            "wearable",
            "sensor",
        ),
    ),
)


LEGACY_KEYWORD_GROUP_NAMES = {
    "Embodied Intelligence",
    "Robotics Core",
    "VLA and Robot Foundation Models",
    "Datasets and Benchmarks",
    "World Models and Data Loop",
    "First Person and UMI",
    "Robot Body and Hardware",
}
